# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynqberry_pinout.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_i2s_adi_0_0/zsys_axi_i2s_adi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_i2s_adi_0_0 || ORIG_REF_NAME==zsys_axi_i2s_adi_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_to_i2s_0_0/zsys_axis_to_i2s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_to_i2s_0_0 || ORIG_REF_NAME==zsys_axis_to_i2s_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_i2s_to_pwm_0_0/zsys_i2s_to_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_i2s_to_pwm_0_0 || ORIG_REF_NAME==zsys_i2s_to_pwm_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xadc_wiz_0_0/zsys_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xadc_wiz_0_0 || ORIG_REF_NAME==zsys_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_reg32_0_0/zsys_axi_reg32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_reg32_0_0 || ORIG_REF_NAME==zsys_axi_reg32_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xbar_0/zsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xbar_0 || ORIG_REF_NAME==zsys_xbar_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys7_0_axi_periph_0/zsys_proc_sys7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys7_0_axi_periph_0 || ORIG_REF_NAME==zsys_proc_sys7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_0 || ORIG_REF_NAME==zsys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_proc_sys7_0_50M_0/zsys_rst_proc_sys7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_proc_sys7_0_50M_0 || ORIG_REF_NAME==zsys_rst_proc_sys7_0_50M_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_interconnect_0_0/zsys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_interconnect_0_0 || ORIG_REF_NAME==zsys_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_vdma_0_0 || ORIG_REF_NAME==zsys_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_data_fifo_0_0 || ORIG_REF_NAME==zsys_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_data_fifo_3_0/zsys_axis_data_fifo_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_data_fifo_3_0 || ORIG_REF_NAME==zsys_axis_data_fifo_3_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_data_fifo_4_0/zsys_axis_data_fifo_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_data_fifo_4_0 || ORIG_REF_NAME==zsys_axis_data_fifo_4_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_raw_demosaic_0_0/zsys_axis_raw_demosaic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_raw_demosaic_0_0 || ORIG_REF_NAME==zsys_axis_raw_demosaic_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_raw_unpack_0_0/zsys_axis_raw_unpack_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_raw_unpack_0_0 || ORIG_REF_NAME==zsys_axis_raw_unpack_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/zsys_csi2_d_phy_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_csi2_d_phy_rx_0_0 || ORIG_REF_NAME==zsys_csi2_d_phy_rx_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_csi_to_axis_0_0/zsys_csi_to_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_csi_to_axis_0_0 || ORIG_REF_NAME==zsys_csi_to_axis_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys_reset_0_0 || ORIG_REF_NAME==zsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys_reset_1_0/zsys_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys_reset_1_0 || ORIG_REF_NAME==zsys_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_Video_IO_2_HDMI_TMDS_0_0/zsys_Video_IO_2_HDMI_TMDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_Video_IO_2_HDMI_TMDS_0_0 || ORIG_REF_NAME==zsys_Video_IO_2_HDMI_TMDS_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_mem_intercon_0/zsys_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_mem_intercon_0 || ORIG_REF_NAME==zsys_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_vdma_0_1 || ORIG_REF_NAME==zsys_axi_vdma_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_fb_conv_0_0/zsys_axis_fb_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_fb_conv_0_0 || ORIG_REF_NAME==zsys_axis_fb_conv_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_clk_wiz_1_0 || ORIG_REF_NAME==zsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/zsys_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zsys_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_v_tc_0_0/zsys_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_v_tc_0_0 || ORIG_REF_NAME==zsys_v_tc_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_0_0/zsys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_0_0 || ORIG_REF_NAME==zsys_xlconcat_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_0/zsys_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_0 || ORIG_REF_NAME==zsys_xlslice_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_1_0/zsys_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_1_0 || ORIG_REF_NAME==zsys_xlslice_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_0 || ORIG_REF_NAME==zsys_auto_pc_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_1/zsys_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_1 || ORIG_REF_NAME==zsys_auto_pc_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_2/zsys_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_2 || ORIG_REF_NAME==zsys_auto_pc_2} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
