# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/zynqberry_0/zynqberry_0.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/zsys_csi2_d_phy_rx_0_0.xci
# IP: The module: 'zsys_csi2_d_phy_rx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/zynqberry_0/zynqberry_0.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_csi2_d_phy_rx_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/parallels/zynqberry_0/zynqberry_0.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/zsys_csi2_d_phy_rx_0_0.xci
# IP: The module: 'zsys_csi2_d_phy_rx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/zynqberry_0/zynqberry_0.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/hdl/csi2_d_phy_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_csi2_d_phy_rx_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
